# my global config
global:
  scrape_interval:     10s
  evaluation_interval: 10s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [localhost:9090]

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 7s
    static_configs:
      - targets: [localhost:9090]